### ISSUE TITLE
Can not view any transaction on transaction list

### ISSUE THREAD

**Issue by tienduongnguyen** [stargately/blockroma#31]
When I try to clone the source code and build, after build, no transaction is displayed

**Comment by doranoda** [comment]
Hi @tienduongnguyen ,

did you follow instructions in https://stargately.com/docs/blockroma/? you need two external dependencies for it to work

1. the database - prepare it as the connection string in the environment variable DATABASE_URL
2. the JSON rpc API - which blockchain are you interacting with?

I would recommend you to schedule a time with our major developer @puncsky  at tianpan.co/calendar
