### ISSUE TITLE
Missing response for eth_getBlockByNumber method

### ISSUE THREAD

**Issue by AtharvDesignString** [stargately/blockroma#44]
Hello I started the indexer but it is giving `Missing response` this error and not making any rpc calls. And I am not sure why you hardcoded value `blockNumberRanges: [[2324586, 2324586]]` in config/default.js

### Environment

* Blockchain: *which blockchain is it?*

I am using goerli and tried with mumbai still getting the same error

* Blockroma Version: *when did you find the problem?*
 
latest

* User Agent: *describe your operating system and browser*

I am using vscode on mac and using chrome. 

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally. A screenshot would be very helpful. If it's UI problem, what is the URL?*

![Screenshot 2023-08-30 at 3 20 11 PM](https://github.com/stargately/blockroma/assets/137756013/164b7ac7-c20b-495d-ae76-dbcc7a9646d3)

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by doranoda** [comment]
yeah, this is a legitimate point - we should clean up the default config

**Comment by doranoda** [comment]
you can set catchup indexer to false to disable the work to catch up previous blocks

**Comment by AtharvDesignString** [comment]
But in indexer I want to store the data of the chain from genesis block to latest block and store it in database so why should I make catchup indexer false, then it will stop the fetching only. And in my case indexer was not making any rpc calls and hence it is not storing any data in the database can you help me with that?

**Comment by doranoda** [comment]
if you want to scan from 0 to latest, you can use the following setup

```
    catchup: {
      enabled: true,
      blocksBatchSize: 200,

      blockNumberRanges: [[0, "latest"]],
    },
```

**Comment by AtharvDesignString** [comment]
Okay will try. Thank you :)
